// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"


///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"
#include "ui_Screen3.h"
#include "ui_Screen2.h"
#include "ui_Screen6.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_image_2_png);    // assets/image 2.png
LV_IMG_DECLARE(ui_img_arrow_3_png);    // assets/Arrow 3.png
LV_IMG_DECLARE(ui_img_image_8_png);    // assets/image 8.png

// FONTS
LV_FONT_DECLARE(ui_font_Montserrat150);
LV_FONT_DECLARE(ui_font_Montserrat60);
LV_FONT_DECLARE(ui_font_Montserrat90);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
