// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

// COMPONENT modSelBtn

lv_obj_t * ui_modSelBtn_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_modSelBtn;
    cui_modSelBtn = lv_btn_create(comp_parent);
    lv_obj_set_width(cui_modSelBtn, 141);
    lv_obj_set_height(cui_modSelBtn, 168);
    lv_obj_set_x(cui_modSelBtn, 16);
    lv_obj_set_y(cui_modSelBtn, 67);
    lv_obj_add_flag(cui_modSelBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_modSelBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_modSelBtn, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_modSelBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_widgetColor);
    ui_object_set_themeable_style_property(cui_modSelBtn, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_widgetColor);
    lv_obj_set_style_shadow_color(cui_modSelBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(cui_modSelBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(cui_modSelBtn, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_widgetColor);
    ui_object_set_themeable_style_property(cui_modSelBtn, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_widgetColor);
    lv_obj_set_style_border_color(cui_modSelBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_opa(cui_modSelBtn, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_width(cui_modSelBtn, 2, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_color(cui_modSelBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(cui_modSelBtn, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_MODSELBTN_NUM);
    children[UI_COMP_MODSELBTN_MODSELBTN] = cui_modSelBtn;
    lv_obj_add_event_cb(cui_modSelBtn, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_modSelBtn, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_modSelBtn_create_hook(cui_modSelBtn);
    return cui_modSelBtn;
}

