// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

// COMPONENT changeScreen

lv_obj_t * ui_changeScreen_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_changeScreen;
    cui_changeScreen = lv_btn_create(comp_parent);
    lv_obj_set_width(cui_changeScreen, 40);
    lv_obj_set_height(cui_changeScreen, 40);
    lv_obj_set_x(cui_changeScreen, 12);
    lv_obj_set_y(cui_changeScreen, 270);
    lv_obj_add_flag(cui_changeScreen, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_changeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(cui_changeScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_widgetColor);
    ui_object_set_themeable_style_property(cui_changeScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_widgetColor);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_CHANGESCREEN_NUM);
    children[UI_COMP_CHANGESCREEN_CHANGESCREEN] = cui_changeScreen;
    lv_obj_add_event_cb(cui_changeScreen, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_changeScreen, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_changeScreen_create_hook(cui_changeScreen);
    return cui_changeScreen;
}

