// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_COMP_SETTINGWIDGET_H
#define _UI_COMP_SETTINGWIDGET_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT settingWidget
#define UI_COMP_SETTINGWIDGET_SETTINGWIDGET 0
#define UI_COMP_SETTINGWIDGET_LABEL5 1
#define UI_COMP_SETTINGWIDGET_SWITCH1 2
#define _UI_COMP_SETTINGWIDGET_NUM 3
lv_obj_t * ui_settingWidget_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
