// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

// COMPONENT settingWidget

lv_obj_t * ui_settingWidget_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_settingWidget;
    cui_settingWidget = lv_btn_create(comp_parent);
    lv_obj_set_width(cui_settingWidget, 450);
    lv_obj_set_height(cui_settingWidget, 50);
    lv_obj_set_x(cui_settingWidget, 0);
    lv_obj_set_y(cui_settingWidget, -72);
    lv_obj_set_align(cui_settingWidget, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_settingWidget, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_settingWidget, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Label5;
    cui_Label5 = lv_label_create(cui_settingWidget);
    lv_obj_set_width(cui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label5, LV_ALIGN_LEFT_MID);
    lv_label_set_text(cui_Label5, "Timer 1");
    lv_obj_set_style_text_font(cui_Label5, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Switch1;
    cui_Switch1 = lv_switch_create(cui_settingWidget);
    lv_obj_set_width(cui_Switch1, 50);
    lv_obj_set_height(cui_Switch1, 25);
    lv_obj_set_align(cui_Switch1, LV_ALIGN_RIGHT_MID);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_SETTINGWIDGET_NUM);
    children[UI_COMP_SETTINGWIDGET_SETTINGWIDGET] = cui_settingWidget;
    children[UI_COMP_SETTINGWIDGET_LABEL5] = cui_Label5;
    children[UI_COMP_SETTINGWIDGET_SWITCH1] = cui_Switch1;
    lv_obj_add_event_cb(cui_settingWidget, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_settingWidget, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_settingWidget_create_hook(cui_settingWidget);
    return cui_settingWidget;
}

