// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_COMP_CHANGESCREEN_H
#define _UI_COMP_CHANGESCREEN_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT changeScreen
#define UI_COMP_CHANGESCREEN_CHANGESCREEN 0
#define _UI_COMP_CHANGESCREEN_NUM 1
lv_obj_t * ui_changeScreen_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
