// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Keyboard2 = NULL;
lv_obj_t * ui_TextArea2 = NULL;
lv_obj_t * ui_changeScreen4 = NULL;
lv_obj_t * ui_Image18 = NULL;
lv_obj_t * ui_changeScreen5 = NULL;
// event funtions
void ui_event_changeScreen4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_changeScreen5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen6, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen6_screen_init);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Screen2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_bgColor);
    ui_object_set_themeable_style_property(ui_Screen2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_bgColor);

    lv_obj_set_style_shadow_color(ui_Screen2, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Screen2, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Keyboard2 = lv_keyboard_create(ui_Screen2);
    lv_keyboard_set_mode(ui_Keyboard2, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_Keyboard2, 480);
    lv_obj_set_height(ui_Keyboard2, 250);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_BOTTOM_MID);
    ui_object_set_themeable_style_property(ui_Keyboard2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_bgColor);
    ui_object_set_themeable_style_property(ui_Keyboard2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_bgColor);

    ui_object_set_themeable_style_property(ui_Keyboard2, LV_PART_ITEMS | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_widgetColor);
    ui_object_set_themeable_style_property(ui_Keyboard2, LV_PART_ITEMS | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_widgetColor);

    ui_TextArea2 = lv_textarea_create(ui_Screen2);
    lv_obj_set_width(ui_TextArea2, 262);
    lv_obj_set_height(ui_TextArea2, LV_SIZE_CONTENT);    /// 87
    lv_obj_set_x(ui_TextArea2, 0);
    lv_obj_set_y(ui_TextArea2, 15);
    lv_obj_set_align(ui_TextArea2, LV_ALIGN_TOP_MID);
    lv_textarea_set_max_length(ui_TextArea2, 6);
    lv_textarea_set_placeholder_text(ui_TextArea2, "Enter Passkey");
    lv_textarea_set_one_line(ui_TextArea2, true);
    lv_textarea_set_password_mode(ui_TextArea2, true);
    lv_obj_set_style_text_color(ui_TextArea2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextArea2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextArea2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_changeScreen4 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_changeScreen4, 40);
    lv_obj_set_height(ui_changeScreen4, 40);
    lv_obj_set_x(ui_changeScreen4, 26);
    lv_obj_set_y(ui_changeScreen4, 14);
    lv_obj_add_flag(ui_changeScreen4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_changeScreen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_changeScreen4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_widgetColor);
    ui_object_set_themeable_style_property(ui_changeScreen4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_widgetColor);

    ui_Image18 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Image18, &ui_img_image_8_png);
    lv_obj_set_width(ui_Image18, LV_SIZE_CONTENT);   /// 23
    lv_obj_set_height(ui_Image18, LV_SIZE_CONTENT);    /// 23
    lv_obj_set_x(ui_Image18, -196);
    lv_obj_set_y(ui_Image18, -126);
    lv_obj_set_align(ui_Image18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image18, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_changeScreen5 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_changeScreen5, 40);
    lv_obj_set_height(ui_changeScreen5, 40);
    lv_obj_set_x(ui_changeScreen5, -16);
    lv_obj_set_y(ui_changeScreen5, 17);
    lv_obj_set_align(ui_changeScreen5, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_changeScreen5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_changeScreen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_changeScreen5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_widgetColor);
    ui_object_set_themeable_style_property(ui_changeScreen5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_widgetColor);

    lv_keyboard_set_textarea(ui_Keyboard2, ui_TextArea2);
    lv_obj_add_event_cb(ui_changeScreen4, ui_event_changeScreen4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_changeScreen5, ui_event_changeScreen5, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_Keyboard2 = NULL;
    ui_TextArea2 = NULL;
    ui_changeScreen4 = NULL;
    ui_Image18 = NULL;
    ui_changeScreen5 = NULL;

}
