// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_modSelBtn = NULL;
lv_obj_t * ui_modSelBtn1 = NULL;
lv_obj_t * ui_modSelBtn2 = NULL;
lv_obj_t * ui_time2 = NULL;
lv_obj_t * ui_date2 = NULL;
// event funtions
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Image2, &ui_img_modeset_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 480
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 320
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button1 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button1, 76);
    lv_obj_set_height(ui_Button1, 52);
    lv_obj_set_x(ui_Button1, -212);
    lv_obj_set_y(ui_Button1, 267);
    lv_obj_set_align(ui_Button1, LV_ALIGN_TOP_MID);
    lv_obj_add_state(ui_Button1, LV_STATE_PRESSED);       /// States
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Button1, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_color(ui_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_Button1, 0, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_modSelBtn = ui_modSelBtn_create(ui_Screen2);
    lv_obj_set_x(ui_modSelBtn, 12);
    lv_obj_set_y(ui_modSelBtn, 76);

    ui_modSelBtn1 = ui_modSelBtn_create(ui_Screen2);
    lv_obj_set_x(ui_modSelBtn1, 169);
    lv_obj_set_y(ui_modSelBtn1, 76);

    ui_modSelBtn2 = ui_modSelBtn_create(ui_Screen2);
    lv_obj_set_x(ui_modSelBtn2, 326);
    lv_obj_set_y(ui_modSelBtn2, 76);

    ui_time2 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_time2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time2, -184);
    lv_obj_set_y(ui_time2, -140);
    lv_obj_set_align(ui_time2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time2, "10:10 AM");
    lv_obj_set_style_text_color(ui_time2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date2 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_date2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_date2, 172);
    lv_obj_set_y(ui_date2, -140);
    lv_obj_set_align(ui_date2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_date2, "01/01/2026");
    lv_obj_set_style_text_color(ui_date2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_date2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_date2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_Image2 = NULL;
    ui_Button1 = NULL;
    ui_modSelBtn = NULL;
    ui_modSelBtn1 = NULL;
    ui_modSelBtn2 = NULL;
    ui_time2 = NULL;
    ui_date2 = NULL;

}
