// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen6 = NULL;
lv_obj_t * ui_time2 = NULL;
lv_obj_t * ui_date2 = NULL;
lv_obj_t * ui_settingsLable = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Button4 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_settingWidget7 = NULL;
// event funtions

// build funtions

void ui_Screen6_screen_init(void)
{
    ui_Screen6 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Screen6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_bgColor);
    ui_object_set_themeable_style_property(ui_Screen6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_bgColor);

    ui_time2 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_time2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time2, -184);
    lv_obj_set_y(ui_time2, -140);
    lv_obj_set_align(ui_time2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time2, "10:10 AM");
    lv_obj_add_flag(ui_time2, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_set_style_text_color(ui_time2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date2 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_date2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_date2, 172);
    lv_obj_set_y(ui_date2, -140);
    lv_obj_set_align(ui_date2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_date2, "01/01/2026");
    lv_obj_add_flag(ui_date2, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_set_style_text_color(ui_date2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_date2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_date2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settingsLable = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_settingsLable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settingsLable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_settingsLable, 0);
    lv_obj_set_y(ui_settingsLable, 10);
    lv_obj_set_align(ui_settingsLable, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_settingsLable, "Settings");
    lv_obj_add_flag(ui_settingsLable, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_set_style_text_color(ui_settingsLable, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_settingsLable, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_settingsLable, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Screen6);
    lv_obj_set_width(ui_Panel1, 480);
    lv_obj_set_height(ui_Panel1, 270);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_flex_flow(ui_Panel1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button4 = lv_btn_create(ui_Panel1);
    lv_obj_set_width(ui_Button4, 450);
    lv_obj_set_height(ui_Button4, 50);
    lv_obj_set_x(ui_Button4, 9);
    lv_obj_set_y(ui_Button4, 11);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_LEFT_MID);

    ui_settingWidget7 = ui_settingWidget_create(ui_Panel1);
    lv_obj_set_x(ui_settingWidget7, 6);
    lv_obj_set_y(ui_settingWidget7, 35);

}

void ui_Screen6_screen_destroy(void)
{
    if(ui_Screen6) lv_obj_del(ui_Screen6);

    // NULL screen variables
    ui_Screen6 = NULL;
    ui_time2 = NULL;
    ui_date2 = NULL;
    ui_settingsLable = NULL;
    ui_Panel1 = NULL;
    ui_Button4 = NULL;
    ui_Label6 = NULL;
    ui_settingWidget7 = NULL;

}
