// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_modSelBtn3 = NULL;
lv_obj_t * ui_modSelBtn4 = NULL;
lv_obj_t * ui_modSelBtn5 = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_Image6 = NULL;
lv_obj_t * ui_Image7 = NULL;
lv_obj_t * ui_Image8 = NULL;
lv_obj_t * ui_Image9 = NULL;
lv_obj_t * ui_Image10 = NULL;
lv_obj_t * ui_Image11 = NULL;
lv_obj_t * ui_Image12 = NULL;
lv_obj_t * ui_Image13 = NULL;
lv_obj_t * ui_time3 = NULL;
lv_obj_t * ui_Image14 = NULL;
lv_obj_t * ui_date3 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_changeScreen1 = NULL;
lv_obj_t * ui_Image16 = NULL;
lv_obj_t * ui_changeScreen2 = NULL;
lv_obj_t * ui_Image17 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_settingsLable2 = NULL;
// event funtions
void ui_event_changeScreen1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_changeScreen2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen2_screen_init);
    }
}

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Screen3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_bgColor);
    ui_object_set_themeable_style_property(ui_Screen3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_bgColor);

    ui_modSelBtn3 = ui_modSelBtn_create(ui_Screen3);
    lv_obj_set_x(ui_modSelBtn3, 326);
    lv_obj_set_y(ui_modSelBtn3, 76);

    ui_modSelBtn4 = ui_modSelBtn_create(ui_Screen3);
    lv_obj_set_x(ui_modSelBtn4, 169);
    lv_obj_set_y(ui_modSelBtn4, 76);

    ui_modSelBtn5 = ui_modSelBtn_create(ui_Screen3);
    lv_obj_set_x(ui_modSelBtn5, 12);
    lv_obj_set_y(ui_modSelBtn5, 76);

    ui_Image3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Image3, &ui_img_image_2_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 43
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 43
    lv_obj_set_x(ui_Image3, 15);
    lv_obj_set_y(ui_Image3, 138);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Image4, &ui_img_image_2_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 43
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 43
    lv_obj_set_x(ui_Image4, 172);
    lv_obj_set_y(ui_Image4, 138);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image5 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Image5, &ui_img_image_2_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 43
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 43
    lv_obj_set_x(ui_Image5, 329);
    lv_obj_set_y(ui_Image5, 138);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image6 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Image6, &ui_img_image_2_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 43
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 43
    lv_obj_set_x(ui_Image6, 108);
    lv_obj_set_y(ui_Image6, 138);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image7 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Image7, &ui_img_image_2_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 43
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 43
    lv_obj_set_x(ui_Image7, 265);
    lv_obj_set_y(ui_Image7, 138);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image8 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Image8, &ui_img_image_2_png);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 43
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 43
    lv_obj_set_x(ui_Image8, 422);
    lv_obj_set_y(ui_Image8, 114);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image9 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Image9, &ui_img_image_2_png);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 43
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 43
    lv_obj_set_x(ui_Image9, 422);
    lv_obj_set_y(ui_Image9, 162);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image10 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Image10, &ui_img_arrow_3_png);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 51
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 15
    lv_obj_set_x(ui_Image10, 58);
    lv_obj_set_y(ui_Image10, 150);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_Image10, 1800);

    ui_Image11 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Image11, &ui_img_arrow_3_png);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 51
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 15
    lv_obj_set_x(ui_Image11, 0);
    lv_obj_set_y(ui_Image11, -7);
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image12 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Image12, &ui_img_arrow_3_png);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 51
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 15
    lv_obj_set_x(ui_Image12, 0);
    lv_obj_set_y(ui_Image12, 7);
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_Image12, 1800);

    ui_Image13 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Image13, &ui_img_arrow_3_png);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 51
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 15
    lv_obj_set_x(ui_Image13, 372);
    lv_obj_set_y(ui_Image13, 136);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_Image13, 1600);

    ui_time3 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_time3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time3, -184);
    lv_obj_set_y(ui_time3, -140);
    lv_obj_set_align(ui_time3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time3, "10:10 AM");
    lv_obj_set_style_text_color(ui_time3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time3, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image14 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Image14, &ui_img_arrow_3_png);
    lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);   /// 51
    lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT);    /// 15
    lv_obj_set_x(ui_Image14, 372);
    lv_obj_set_y(ui_Image14, 160);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_Image14, 2000);

    ui_date3 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_date3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_date3, 172);
    lv_obj_set_y(ui_date3, -140);
    lv_obj_set_align(ui_date3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_date3, "01/01/2026");
    lv_obj_set_style_text_color(ui_date3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_date3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_date3, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 49);
    lv_obj_set_y(ui_Label1, 94);
    lv_label_set_text(ui_Label1, "MODE: A");

    ui_Label2 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 211);
    lv_obj_set_y(ui_Label2, 94);
    lv_label_set_text(ui_Label2, "MODE: B");

    ui_Label3 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 364);
    lv_obj_set_y(ui_Label3, 94);
    lv_label_set_text(ui_Label3, "MODE: C");

    ui_changeScreen1 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_changeScreen1, 40);
    lv_obj_set_height(ui_changeScreen1, 40);
    lv_obj_set_x(ui_changeScreen1, 12);
    lv_obj_set_y(ui_changeScreen1, 270);
    lv_obj_add_flag(ui_changeScreen1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_changeScreen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_changeScreen1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_widgetColor);
    ui_object_set_themeable_style_property(ui_changeScreen1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_widgetColor);

    ui_Image16 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Image16, &ui_img_image_8_png);
    lv_obj_set_width(ui_Image16, LV_SIZE_CONTENT);   /// 23
    lv_obj_set_height(ui_Image16, LV_SIZE_CONTENT);    /// 23
    lv_obj_set_x(ui_Image16, 20);
    lv_obj_set_y(ui_Image16, 278);
    lv_obj_add_flag(ui_Image16, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_changeScreen2 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_changeScreen2, 40);
    lv_obj_set_height(ui_changeScreen2, 40);
    lv_obj_set_x(ui_changeScreen2, 427);
    lv_obj_set_y(ui_changeScreen2, 270);
    lv_obj_add_flag(ui_changeScreen2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_changeScreen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_changeScreen2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_widgetColor);
    ui_object_set_themeable_style_property(ui_changeScreen2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_widgetColor);

    ui_Image17 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Image17, &ui_img_arrow_3_png);
    lv_obj_set_width(ui_Image17, LV_SIZE_CONTENT);   /// 51
    lv_obj_set_height(ui_Image17, LV_SIZE_CONTENT);    /// 15
    lv_obj_set_x(ui_Image17, 206);
    lv_obj_set_y(ui_Image17, 130);
    lv_obj_set_align(ui_Image17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image17, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_Image17, 1800);
    lv_img_set_zoom(ui_Image17, 150);

    ui_Label4 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 0);
    lv_obj_set_y(ui_Label4, -20);
    lv_obj_set_align(ui_Label4, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label4, "MODES");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settingsLable2 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_settingsLable2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settingsLable2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_settingsLable2, 0);
    lv_obj_set_y(ui_settingsLable2, 10);
    lv_obj_set_align(ui_settingsLable2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_settingsLable2, "Settings");
    lv_obj_set_style_text_color(ui_settingsLable2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_settingsLable2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_settingsLable2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_changeScreen1, ui_event_changeScreen1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_changeScreen2, ui_event_changeScreen2, LV_EVENT_ALL, NULL);

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_modSelBtn3 = NULL;
    ui_modSelBtn4 = NULL;
    ui_modSelBtn5 = NULL;
    ui_Image3 = NULL;
    ui_Image4 = NULL;
    ui_Image5 = NULL;
    ui_Image6 = NULL;
    ui_Image7 = NULL;
    ui_Image8 = NULL;
    ui_Image9 = NULL;
    ui_Image10 = NULL;
    ui_Image11 = NULL;
    ui_Image12 = NULL;
    ui_Image13 = NULL;
    ui_time3 = NULL;
    ui_Image14 = NULL;
    ui_date3 = NULL;
    ui_Label1 = NULL;
    ui_Label2 = NULL;
    ui_Label3 = NULL;
    ui_changeScreen1 = NULL;
    ui_Image16 = NULL;
    ui_changeScreen2 = NULL;
    ui_Image17 = NULL;
    ui_Label4 = NULL;
    ui_settingsLable2 = NULL;

}
