// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Keyboard2;
extern lv_obj_t * ui_TextArea2;
extern void ui_event_changeScreen4(lv_event_t * e);
extern lv_obj_t * ui_changeScreen4;
extern lv_obj_t * ui_Image18;
extern void ui_event_changeScreen5(lv_event_t * e);
extern lv_obj_t * ui_changeScreen5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

